### PR TITLE
Implement new file menu

### PR DESCRIPTION
**Pull request by skjnldsv**
Capture d’écran_2022-06-09_11-26-45

```js
import { addNewFileMenuEntry } from '/home/admin/git/nextcloud-files/dist/index'
import FolderPlus from '@mdi/svg/svg/folder-plus.svg'

addNewFileMenuEntry({
	id: 'new-folder',
	displayName: 'Create folder',
	templateName: 'New folder',
	iconSvgInline: FolderPlus,
	fileType: 'folder',
	handler: console.info,
})
```

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
See comments

**Comment by skjnldsv** [comment]
> for other places it might make sense to allow passing a vue component from the material icons library as well

Well, this is actually also using the material design icon library.
`import FolderPlus from '@mdi/svg/svg/folder-plus.svg'`

With such component, we could theoretically even stop using the material design library for APIs and use this pattern instead :thinking:

**Comment by juliushaertl** [comment]
> Well, this is actually also using the material design icon library.

Sorry I meant the vue-material-design-icons one to not need a second library, but I think this is fine as it is for the new file menu. We may still consider that if we find a use case for it ;)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/calendar/pull/4251
@sazanof  please have a look :)

**Comment by sazanof** [comment]
> [nextcloud/calendar#4251](https://github.com/nextcloud/calendar/pull/4251) @sazanof please have a look :)

Hello @skjnldsv ! I have read the code and the screenshot. That's cool! It's cool that there is an opportunity to customize and stylize the menu as much as possible and set your own handler for each item.  
I think it is very universal, what is needed now!

**Comment by skjnldsv** [comment]
> Hello @skjnldsv ! I have read the code and the screenshot. That's cool! It's cool that there is an opportunity to customize and stylize the menu as much as possible and set your own handler for each item. I think it is very universal, what is needed now!

Nice! Do you think it fits all of your requirements? Any changes you would like to see?

**Comment by sazanof** [comment]
> Nice! Do you think it fits all of your requirements? Any changes you would like to see?

Hello, @skjnldsv !

**Well, let's go** (all of the following is sucked out of the finger, but nevertheless it will be nice if it somehow comes in handy). =)

If there are additional requests, they relate to the display of the download process for each downloaded file. It would also be nice to somehow visualize the start of the upload (for example, a placeholder that is inserted into the place of the future file. How can this be implemented in theory? 

Again, I understand that this component is only for upload. Nevertheless, I will ask.
In your component, you can also use "Select from files" (for example). So, I ran into a problem (well, not really a problem, just a nuance): I would like to display visually (preloader, placeholder) the start of loading after selecting a document from files.

Well, the question in general is how to then use your component to update the visual list of selected files or attachments? Will it be possible?

It would also be nice to have methods in your API for loading not only DAV, but also loading attachments when writing a letter (https://github.com/nextcloud/mail/issues/5768#issuecomment-990920989). Ideally in the future use your API to upload/select everything in NC.

Also, most likely, "Upload files" will need to be replaced with "Upload from device" (here you need a fresh design look and the opinion of your colleagues) 

On the other hand, I understand that this is just a component to upload and perhaps it is not worth inflating it with functionality.

**Pull request merged**
