### PR TITLE
Init tx config

### PR DESCRIPTION
**Pull request by skjnldsv**
@Valdnet @rakekniven does this looks good to you?

### CODE REVIEW

**Comment by rakekniven** [comment]
Not sure if this is necessary here.

You wrote at #29 :

> We cannot use the usual translation process as this is a library and loading translations differently.

> Transifex is pulling changes from github and is automatically opening PRs here.
> No need for docker or the usual bot to do anything

**Comment by skjnldsv** [comment]
> Not sure if this is necessary here.

It's a good question. I am still unsure if the github-> transifex sync is working (I manually uploaded it for now)
I need to test that out for https://www.transifex.com/nextcloud/nextcloud-upload-library/settings/integrations/

**Comment by skjnldsv** [comment]
Currently, it state 
image

The second part seems to indicate it's not working.
But it also seems there are other point of sync in transifex, like https://docs.transifex.com/projects/updating-content/#automatically-updating-source-files

image

Transifex is powerful but confusing sometimes

**Comment by skjnldsv** [comment]
I enabled this for the upload library
image

Let's see in 6h if that works

> Transifex will check that URL for updates 4 times per day (every 6 hours) and if there are any changes to the file, it'll fetch the file and update the resource in Transifex. Because the check happens 4 times a day, there may be a delay between when you update a file and when Transifex detects the changes. The updated resource will automatically be available to your translators and reviewers.

**Comment by skjnldsv** [comment]
> Why do you go a different way compared to the other resources?

Well, why we have a kinda working workflow for apps, libraries are still a bit weird imho.
I am investigating this. Will post some proper guidelines once this work

**Comment by Valdnet** [comment]
> Transifex will check that URL for updates 4 times per day (every 6 hou

Is it not too often? In my opinion, once a day is enough, preferably at night.

**Comment by skjnldsv** [comment]
> > Transifex will check that URL for updates 4 times per day (every 6 hours)
> 
> Is it not too often? In my opinion, once a day is enough, preferably at night.

Not configurable :)
It's only pulling changes

**Comment by skjnldsv** [comment]
Not needed, works
image

**Pull request closed without merging**
